import { promises as fs } from 'fs';
import * as path from 'path';

export interface PlanArtifact {
  /** Workspace-relative path, suitable for prompts and UI notices. */
  relativePath: string;
  /** The complete Markdown saved to disk. */
  markdown: string;
}

function safePart(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^[-.]+|[-.]+$/g, '');
  return cleaned || 'session';
}

/**
 * Persist the latest Plan-mode answer for a chat. Plan mode itself remains read-only;
 * this is the single extension-owned artifact it is allowed to create.
 */
export async function savePlanArtifact(
  repoRoot: string,
  sessionId: string,
  title: string,
  content: string,
): Promise<PlanArtifact> {
  const relativePath = path.join('.sema', 'plans', `${safePart(sessionId)}.md`);
  const absolutePath = path.join(repoRoot, relativePath);
  const heading = title.trim() && title !== 'New chat' ? title.trim() : 'Implementation plan';
  const markdown =
    `# ${heading}\n\n` +
    `<!-- Generated by sema Plan mode; session: ${safePart(sessionId)} -->\n\n` +
    `${content.trim()}\n`;
  await fs.mkdir(path.dirname(absolutePath), { recursive: true });
  const tmp = `${absolutePath}.tmp`;
  await fs.writeFile(tmp, markdown, 'utf8');
  await fs.rename(tmp, absolutePath);
  return { relativePath, markdown };
}

/** Read a plan only when it resolves inside this workspace. */
export async function readPlanArtifact(repoRoot: string, relativePath: string): Promise<string> {
  const root = path.resolve(repoRoot);
  const absolute = path.resolve(root, relativePath);
  if (absolute !== root && !absolute.startsWith(root + path.sep)) {
    return '';
  }
  try {
    return await fs.readFile(absolute, 'utf8');
  } catch {
    return '';
  }
}
