"""PATH shims — the enforcement mechanism, not just the documented interface.

Generates thin wrapper scripts for gated binaries (kubectl, terraform, aws,
helm, ...) that route through the analyze-first gate no matter which tool
invoked them: sema's own MCP tool, a generic shell/terminal tool the AI
provider happens to have, or a human typing directly. See
docs/devops-guard-plan.md, "Making the gate actually unbypassable".

The real binary's absolute path is resolved once, at install time, and baked
into the shim — this avoids any PATH-ordering ambiguity at run time about
which `kubectl` is "real".
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

_SHIM_TEMPLATE = """#!/usr/bin/env bash
# Generated by `sema devops install-shims` — do not edit by hand.
# Routes every invocation of {name} through sema's analyze-first gate.
set -euo pipefail

REAL_BIN="{real_bin}"

if ! command -v sema >/dev/null 2>&1; then
    # Fail closed: if the gate can't be reached, refuse rather than exec the
    # real binary unguarded.
    echo "sema devops guard: 'sema' not found on PATH — refusing to run {name} unguarded" >&2
    exit 127
fi

exec sema devops guard-shim "$REAL_BIN" -- "$@"
"""


def _find_real_binary(name: str, exclude_dir: Path) -> str | None:
    """Find `name` on PATH, skipping any entry under exclude_dir (the shim dir itself)."""
    exclude = str(exclude_dir.resolve())
    for entry in os.environ.get("PATH", "").split(os.pathsep):
        if not entry or str(Path(entry).resolve()) == exclude:
            continue
        candidate = Path(entry) / name
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate.resolve())
    return None


def install_shims(shim_dir: Path, names: list[str]) -> dict[str, str]:
    """Write a shim script per binary in `names` that's actually found on PATH.

    Returns {name: real_binary_path} for whatever was installed. Binaries not
    present on the system are skipped, not errored — not every engineer has
    every tool installed.
    """
    shim_dir.mkdir(parents=True, exist_ok=True)
    installed = {}
    for name in names:
        real_bin = _find_real_binary(name, shim_dir)
        if real_bin is None:
            continue
        script_path = shim_dir / name
        script_path.write_text(_SHIM_TEMPLATE.format(name=name, real_bin=real_bin))
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        installed[name] = real_bin
    return installed
