"""Plan-mode artifacts — the Python port of ``planArtifact.ts``.

Plan mode stays read-only over source; this file is the one artifact it is
allowed to create, written to ``.sema/plans/<session>.md``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

_UNSAFE = re.compile(r"[^a-zA-Z0-9._-]+")


@dataclass
class PlanArtifact:
    relative_path: str
    markdown: str


def _safe_part(value: str) -> str:
    cleaned = _UNSAFE.sub("-", value).strip("-.")
    return cleaned or "session"


def save_plan(repo_root: Path, session_id: str, title: str, content: str) -> PlanArtifact:
    relative = Path(".sema") / "plans" / f"{_safe_part(session_id)}.md"
    absolute = repo_root / relative
    heading = title.strip() if title.strip() and title != "New chat" else "Implementation plan"
    markdown = (
        f"# {heading}\n\n"
        f"<!-- Generated by sema Plan mode; session: {_safe_part(session_id)} -->\n\n"
        f"{content.strip()}\n"
    )
    absolute.parent.mkdir(parents=True, exist_ok=True)
    tmp = absolute.with_suffix(".md.tmp")
    tmp.write_text(markdown, encoding="utf-8")
    tmp.replace(absolute)
    return PlanArtifact(relative_path=str(relative), markdown=markdown)


def read_plan(repo_root: Path, relative_path: str) -> str:
    """Read a plan only when it resolves inside this workspace."""
    root = repo_root.resolve()
    absolute = (root / relative_path).resolve()
    if absolute != root and root not in absolute.parents:
        return ""
    try:
        return absolute.read_text(encoding="utf-8")
    except OSError:
        return ""
